### ISSUE TITLE
UnComplicatedCustomRoles

### ISSUE THREAD

**Issue by Epsilon11Apex** [UncomplicatedCustomServer/UncomplicatedCustomRoles#31]
Ok so, it's not very useful but if you want, i got some template custom role. ![Config.CustomRôlesTemplate.zip](https://github.com/user-attachments/files/15862111/Config.CustomRolesTemplate.zip)

**Comment by FoxWorn3365** [comment]
Nah, can be useful.
I'll probably add some of them in the default config within the next relase

**Comment by FoxWorn3365** [comment]
obsolete
